# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto


class Migration(migrations.Migration):

    dependencies = [
        ('lumose', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default='./lumose/static/imageNotFound.jpg', storage=storages.backends.s3boto.S3BotoStorage(acl='private', querystring_auth=True, querystring_expire=600), upload_to=''),
        ),
    ]
